category_1 = Category.create(name: 'Pets')
gif_1 = category_1.gifs.create(image_path: "https://media2.giphy.com/media/lHsCS3IickU7e/giphy.gif")
gif_2 = category_1.gifs.create(image_path: "https://media0.giphy.com/media/h8E7oT2FGEJkQ/giphy.gif")
gif_3 = category_1.gifs.create(image_path: "https://media3.giphy.com/media/qPuhFBQt8xLEY/giphy.webp") 
gif_4 = category_1.gifs.create(image_path: "https://media3.giphy.com/media/qPuhFBQt8xLEY/giphy.gif")

category_2 = Category.create(name: 'Food')
gif_5 = category_2.gifs.create(image_path: "https://media.giphy.com/media/3osxY7eI6enqNBo2mQ/giphy.gif")
gif_6 = category_2.gifs.create(image_path: "https://media0.giphy.com/media/o0ZrmGRXiqVRm/giphy.gif")
gif_7 = category_2.gifs.create(image_path: "https://media2.giphy.com/media/L2kz4V3Mr7QyY/giphy.gif")
gif_8 = category_2.gifs.create(image_path: "https://media2.giphy.com/media/ef61oIGVyckY8/giphy.gif")

category_3 = Category.create(name: 'Music')
gif_9 = category_3.gifs.create(image_path: "https://media2.giphy.com/media/l2JhGk8rR9WFLEDQY/giphy.gif")
gif_10 = category_3.gifs.create(image_path: "https://media1.giphy.com/media/8nhgZZMKUicpi/giphy.gif")
gif_11 = category_3.gifs.create(image_path: "https://media2.giphy.com/media/3o72EX5QZ9N9d51dqo/giphy.gif")
gif_12 = category_3.gifs.create(image_path: "https://media3.giphy.com/media/3lxD1O74siiz5FvrJs/giphy.gif")

category_4 = Category.create(name: 'Dance')
gif_13 = category_4.gifs.create(image_path: "https://media1.giphy.com/media/xJjs8eGVbjNYY/giphy.gif")
gif_14 = category_4.gifs.create(image_path: "https://media.giphy.com/media/6fScAIQR0P0xW/giphy.gif")
gif_15 = category_4.gifs.create(image_path: "https://media3.giphy.com/media/3rgXBvnbXtxwaWmhr2/giphy.gif")
gif_16 = category_4.gifs.create(image_path: "https://media2.giphy.com/media/l3vRlT2k2L35Cnn5C/giphy.gif")

category_5 = Category.create(name: 'Sleep')
gif_17 = category_5.gifs.create(image_path: "https://media1.giphy.com/media/YZKpLuYQ5TKKc/giphy.gif")
gif_18 = category_5.gifs.create(image_path: "https://media0.giphy.com/media/10jniOyQtffjbO/giphy.gif")
gif_19 = category_5.gifs.create(image_path: "https://media0.giphy.com/media/xT8qBvH1pAhtfSx52U/giphy.gif")
gif_20 = category_5.gifs.create(image_path: "https://media2.giphy.com/media/Avwm4ZRDV0c9O/giphy.gif")
